#!/usr/bin/env python3
"""Map WikiTicket SDD / worklog items (or GitHub Issues) to OKF TicketLink concepts.

Usage:
  # From worklog fold JSON on stdin or --worklog-fold file
  bin/worklog fold | python3 scripts/pkc_ticket_link.py emit --bundle sample-okf

  # Single item
  python3 scripts/pkc_ticket_link.py emit --bundle sample-okf \\
      --id 01KYQZ4PAMZCM9N56K8F3034F2 --title "My item" --status todo

  # Dry-run (print paths only)
  ... emit --dry-run
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def slugify(title: str) -> str:
    s = title.lower().strip()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")[:60] or "ticket"


def status_map(worklog_status: str) -> str:
    return {
        "todo": "open",
        "in_progress": "in_progress",
        "blocked": "blocked",
        "done": "done",
        "cancelled": "cancelled",
    }.get(worklog_status or "todo", worklog_status or "open")


def render_ticket(
    *,
    title: str,
    body: str,
    item_id: str,
    status: str,
    external_system: str,
    external_id: str,
    github_url: str | None,
    maps_to: list[str],
) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    maps_block = "\n".join(f"- [{Path(p).stem}]({p if p.startswith('/') else '/' + p})" for p in maps_to) or "- TODO"
    gh_line = f"\n- GitHub: {github_url}" if github_url else ""
    return f"""---
type: TicketLink
title: {title}
description: {body.splitlines()[0] if body else title}
tags: [ticket, worklog, sldc]
timestamp: {ts}
status: {status_map(status)}
external_id: {external_id}
external_system: {external_system}
worklog_id: {item_id}
verified: true
links:
  - target: /knowledge/okf-conventions.md
    rel: documents
---

# {title}

## External reference

- System: {external_system}
- ID: `{external_id}`
- Worklog ULID: `{item_id}`{gh_line}

## Summary

{body or title}

## Maps to OKF concepts

{maps_block}

## Notes

Generated by `scripts/pkc_ticket_link.py` from WikiTicket SDD / worklog.
"""


def load_items(args: argparse.Namespace) -> list[dict]:
    if args.id:
        return [
            {
                "id": args.id,
                "title": args.title or args.id,
                "body": args.body or "",
                "status": args.status or "todo",
                "external": {"system": "github", "key": args.github_issue} if args.github_issue else {},
            }
        ]
    raw = Path(args.worklog_fold).read_text() if args.worklog_fold else sys.stdin.read()
    if not raw.strip():
        return []
    data = json.loads(raw)
    if isinstance(data, dict):
        data = list(data.values())
    return data


def emit(args: argparse.Namespace) -> int:
    bundle = Path(args.bundle)
    tickets_dir = bundle / "tickets"
    tickets_dir.mkdir(parents=True, exist_ok=True)
    items = load_items(args)
    if not items:
        print(json.dumps({"error": "no items", "hint": "pipe bin/worklog fold or pass --id"}))
        return 1

    written = []
    for it in items:
        if args.open_only and it.get("status") in ("done", "cancelled"):
            continue
        item_id = it.get("id") or it.get("item")
        if not item_id:
            continue
        title = it.get("title") or item_id
        body = it.get("body") or ""
        status = it.get("status") or "todo"
        ext = it.get("external") or {}
        # external may be nested from fold
        if isinstance(ext, dict):
            ext_system = ext.get("system") or "worklog"
            ext_key = ext.get("key") or item_id
        else:
            ext_system, ext_key = "worklog", item_id
        gh_url = None
        if ext_system == "github" and ext_key:
            # key may be "12" or full
            if str(ext_key).isdigit():
                project = args.github_project or "SpillwaveSolutions/okf-plugin"
                gh_url = f"https://github.com/{project}/issues/{ext_key}"
                ext_key = str(ext_key)
        slug = slugify(title)
        path = tickets_dir / f"{slug}.md"
        content = render_ticket(
            title=title,
            body=body,
            item_id=item_id,
            status=status,
            external_system=ext_system if ext_system != "none" else "worklog",
            external_id=str(ext_key),
            github_url=gh_url,
            maps_to=args.maps_to or [],
        )
        if args.dry_run:
            written.append({"path": str(path), "id": item_id, "dry_run": True})
            continue
        path.write_text(content, encoding="utf-8")
        written.append({"path": str(path), "id": item_id})

    # refresh tickets index lightly
    index = tickets_dir / "index.md"
    if not args.dry_run and written:
        lines = [
            "---",
            "title: Tickets catalog",
            "description: TicketLink concepts bridging OKF graphs to worklog / SLDC systems.",
            f"timestamp: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
            "---",
            "",
            "# Tickets",
            "",
        ]
        for w in sorted(written, key=lambda x: x["path"]):
            p = Path(w["path"])
            rel = "/" + p.relative_to(bundle).as_posix()
            # title from filename
            lines.append(f"- [{p.stem}]({rel})")
        # keep prior entries if any md not just written
        existing = sorted(tickets_dir.glob("*.md"))
        for p in existing:
            if p.name == "index.md":
                continue
            rel = "/" + p.relative_to(bundle).as_posix()
            entry = f"- [{p.stem}]({rel})"
            if entry not in lines:
                lines.append(entry)
        index.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(json.dumps({"written": written, "count": len(written)}, indent=2))
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description="OKF TicketLink ↔ worklog helpers")
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("emit", help="Emit TicketLink markdown from worklog items")
    s.add_argument("--bundle", required=True, help="OKF bundle root (e.g. sample-okf or .okf)")
    s.add_argument("--worklog-fold", help="JSON file from worklog fold (default: stdin)")
    s.add_argument("--id", help="Single worklog ULID")
    s.add_argument("--title")
    s.add_argument("--body")
    s.add_argument("--status", default="todo")
    s.add_argument("--github-issue", help="GitHub issue number")
    s.add_argument("--github-project", default="SpillwaveSolutions/okf-plugin")
    s.add_argument("--maps-to", action="append", default=[], help="OKF concept path to link")
    s.add_argument("--open-only", action="store_true", help="Skip done/cancelled items")
    s.add_argument("--dry-run", action="store_true")
    args = p.parse_args()
    if args.cmd == "emit":
        return emit(args)
    return 1


if __name__ == "__main__":
    sys.exit(main())
